from __future__ import annotations

import subprocess
from dataclasses import dataclass

from .checks_runner import CheckResult, run_checks
from .executors.base import Executor
from .github_client import GitHubClient, IssueRef
from .logging_setup import get_logger
from .prompt_builder import build_initial, build_retry
from .retry_policy import RetryPolicy
from .worktree_manager import Worktree, WorktreeManager

log = get_logger()


@dataclass
class TaskOutcome:
    issue_number: int
    success: bool
    attempts: int
    pr_url: str | None
    summary: str


class Orchestrator:
    def __init__(
        self,
        gh: GitHubClient,
        worktrees: WorktreeManager,
        executor: Executor,
        retry: RetryPolicy,
        check_commands: list[list[str]],
        executor_timeout_sec: int,
        push_remote: str = "origin",
    ) -> None:
        self.gh = gh
        self.worktrees = worktrees
        self.executor = executor
        self.retry = retry
        self.check_commands = check_commands
        self.executor_timeout_sec = executor_timeout_sec
        self.push_remote = push_remote

    def process(self, issue: IssueRef) -> TaskOutcome:
        if not self.gh.claim(issue.number):
            log.info("skip_not_claimable", issue=issue.number)
            return TaskOutcome(issue.number, False, 0, None, "Could not claim issue")

        wt: Worktree | None = None
        try:
            wt = self.worktrees.create(issue.number, issue.title)
            log.info("worktree_created", issue=issue.number, path=str(wt.path), branch=wt.branch)

            base_prompt = build_initial(issue, self.check_commands)
            prompt = base_prompt
            last_check: CheckResult | None = None
            attempt = 0

            while True:
                attempt += 1
                log.info("executor_run", issue=issue.number, attempt=attempt)
                exec_result = self.executor.run(prompt, wt.path, self.executor_timeout_sec)
                log.info(
                    "executor_done",
                    issue=issue.number,
                    attempt=attempt,
                    ok=exec_result.ok,
                    exit_code=exec_result.exit_code,
                )

                last_check = run_checks(self.check_commands, wt.path)
                log.info(
                    "checks_done",
                    issue=issue.number,
                    attempt=attempt,
                    ok=last_check.ok,
                    command=last_check.command,
                )

                if last_check.ok:
                    break
                if not self.retry.should_retry(attempt):
                    break
                prompt = build_retry(
                    base_prompt,
                    attempt=attempt,
                    command=last_check.command,
                    stdout=last_check.stdout,
                    stderr=last_check.stderr,
                )

            assert last_check is not None
            if not last_check.ok:
                summary = (
                    f"Failed after {attempt} attempt(s).\n"
                    f"Last command: `{last_check.command}`\n\n"
                    f"```\n{last_check.stderr[-3000:] or last_check.stdout[-3000:]}\n```"
                )
                self.gh.mark_failed(issue.number, summary)
                return TaskOutcome(issue.number, False, attempt, None, summary)

            self._push(wt)
            pr_title = f"[#{issue.number}] {issue.title}"
            pr_body = (
                f"Resolves #{issue.number}\n\n"
                f"Mrglglgl! Generated by Murloc Manager in {attempt} attempt(s).\n\n"
                f"Checks passed:\n"
                + "\n".join(f"- `{' '.join(c)}`" for c in self.check_commands)
            )
            pr_url = self.gh.open_pr(issue.number, wt.branch, pr_title, pr_body)
            review_summary = f"Attempts: {attempt}. Last check: `{last_check.command}` ✓"
            self.gh.mark_review(issue.number, pr_url, review_summary)

            self.worktrees.cleanup(issue.number)
            return TaskOutcome(issue.number, True, attempt, pr_url, review_summary)
        except Exception as e:
            log.exception("orchestrator_error", issue=issue.number)
            self.gh.mark_failed(issue.number, f"Orchestrator error: {e!r}")
            # Leave worktree for inspection on errors.
            return TaskOutcome(issue.number, False, 0, None, f"Error: {e!r}")

    def _push(self, wt: Worktree) -> None:
        subprocess.run(
            ["git", "push", "-u", self.push_remote, wt.branch],
            cwd=str(wt.path),
            check=True,
            capture_output=True,
            text=True,
        )
