from __future__ import annotations

import subprocess
from dataclasses import dataclass

from .executors.base import Executor
from .github_client import GitHubClient, IssueRef
from .issue_classifier import classify
from .logging_setup import get_logger
from .prompt_builder import build_initial
from .worktree_manager import Worktree, WorktreeManager

log = get_logger()


@dataclass
class TaskOutcome:
    issue_number: int
    success: bool
    pr_url: str | None
    summary: str


class Orchestrator:
    """Murloc only watches the board. It claims an issue, opens a worktree on a
    conventionally-named branch, hands the issue off to the executor, then —
    if the agent produced commits — pushes and opens a PR. It does not run
    tests or checks; that is the agent's responsibility.
    """

    def __init__(
        self,
        gh: GitHubClient,
        worktrees: WorktreeManager,
        executor: Executor,
        executor_timeout_sec: int,
        push_remote: str = "origin",
    ) -> None:
        self.gh = gh
        self.worktrees = worktrees
        self.executor = executor
        self.executor_timeout_sec = executor_timeout_sec
        self.push_remote = push_remote

    def process(self, issue: IssueRef) -> TaskOutcome:
        if not self.gh.claim(issue.number):
            log.info("skip_not_claimable", issue=issue.number)
            return TaskOutcome(issue.number, False, None, "Could not claim issue")

        type_ = classify(issue)
        log.info("classified", issue=issue.number, type=type_)

        wt: Worktree | None = None
        try:
            wt = self.worktrees.create(type_, issue.number, issue.title)
            log.info("worktree_created", issue=issue.number, path=str(wt.path), branch=wt.branch)

            prompt = build_initial(issue)
            log.info("executor_run", issue=issue.number, branch=wt.branch)
            exec_result = self.executor.run(prompt, wt.path, self.executor_timeout_sec)
            log.info(
                "executor_done",
                issue=issue.number,
                ok=exec_result.ok,
                exit_code=exec_result.exit_code,
            )

            if not exec_result.ok:
                summary = (
                    f"Agent exited with code {exec_result.exit_code}.\n\n"
                    f"```\n{exec_result.stderr[-3000:] or exec_result.stdout[-3000:]}\n```"
                )
                self.gh.mark_failed(issue.number, summary)
                return TaskOutcome(issue.number, False, None, summary)

            commits = self._commits_ahead(wt)
            if commits == 0:
                summary = "Agent exited cleanly but produced no commits — nothing to ship."
                self.gh.mark_failed(issue.number, summary)
                return TaskOutcome(issue.number, False, None, summary)

            self._push(wt)
            subject, body = self._first_commit_message(wt)
            pr_title = subject or f"{type_}: {issue.title}"
            pr_body = self._compose_pr_body(body, issue.number, commits)
            pr_url = self.gh.open_pr(issue.number, wt.branch, pr_title, pr_body)
            review_summary = f"PR opened with {commits} commit(s) on `{wt.branch}`."
            self.gh.mark_review(issue.number, pr_url, review_summary)

            self.worktrees.cleanup(issue.number)
            return TaskOutcome(issue.number, True, pr_url, review_summary)
        except Exception as e:
            log.exception("orchestrator_error", issue=issue.number)
            self.gh.mark_failed(issue.number, f"Orchestrator error: {e!r}")
            return TaskOutcome(issue.number, False, None, f"Error: {e!r}")

    @staticmethod
    def _compose_pr_body(agent_body: str, issue_number: int, commits: int) -> str:
        footer = (
            f"---\n"
            f"Resolves #{issue_number}\n"
            f"Mrglglgl! Generated by Murloc Manager · {commits} commit(s).\n"
        )
        if agent_body.strip():
            return f"{agent_body.rstrip()}\n\n{footer}"
        return footer

    def _first_commit_message(self, wt: Worktree) -> tuple[str, str]:
        """Return (subject, body) of the oldest commit on the branch ahead of base."""
        proc = subprocess.run(
            [
                "git", "log",
                f"{self.worktrees.base_branch}..HEAD",
                "--reverse",
                "--format=%B%x00",
            ],
            cwd=str(wt.path),
            check=True,
            capture_output=True,
            text=True,
        )
        chunks = [c for c in proc.stdout.split("\x00") if c.strip()]
        if not chunks:
            return "", ""
        first = chunks[0].strip("\n")
        if "\n" in first:
            subject, body = first.split("\n", 1)
            return subject.strip(), body.lstrip("\n")
        return first.strip(), ""

    def _commits_ahead(self, wt: Worktree) -> int:
        proc = subprocess.run(
            ["git", "rev-list", "--count", f"{self.worktrees.base_branch}..HEAD"],
            cwd=str(wt.path),
            check=True,
            capture_output=True,
            text=True,
        )
        return int(proc.stdout.strip() or "0")

    def _push(self, wt: Worktree) -> None:
        subprocess.run(
            ["git", "push", "-u", self.push_remote, wt.branch],
            cwd=str(wt.path),
            check=True,
            capture_output=True,
            text=True,
        )
